### ISSUE TITLE
thread 'Inscription indexing runloop' panicked at 'index out of bounds'

### ISSUE THREAD

**Issue by 4ker-dep** [hirosystems/bitcoin-indexer#233]
Hi! I'm running ordhook v1.2.0 in a k8s cluster on AWS. I've successfully passed the on-chain data scraping the from a Bitcoin daemon but currently I've getting the following error:
```
{"msg":"Unable to find block #337489, will retry in 2.479s","level":"WARN","ts":"2023-12-15T16:30:03.450302565Z"}
{"msg":"Unable to find block #337489, will retry in 6.8s","level":"WARN","ts":"2023-12-15T16:30:05.929453541Z"}
{"msg":"Unable to find block #337489, will retry in 15.831s","level":"WARN","ts":"2023-12-15T16:30:12.729600261Z"}
{"msg":"Unable to find block #337489, will retry in 2.372s","level":"WARN","ts":"2023-12-15T16:30:28.577820567Z"}
{"msg":"Unable to find block #337489, will retry in 6.392s","level":"WARN","ts":"2023-12-15T16:30:30.949958675Z"}
{"msg":"Unable to find block #337489, will retry in 16.042s","level":"WARN","ts":"2023-12-15T16:30:37.342022251Z"}
{"msg":"Unable to find block #337489, will retry in 2.653s","level":"WARN","ts":"2023-12-15T16:30:53.391773419Z"}
{"msg":"Unable to find block #337489, will retry in 5.461s","level":"WARN","ts":"2023-12-15T16:30:56.044894169Z"}
{"msg":"Unable to find block #337489, will retry in 13.126s","level":"WARN","ts":"2023-12-15T16:31:01.506024575Z"}
{"msg":"Unable to find block #337489, will retry in 2.14s","level":"WARN","ts":"2023-12-15T16:31:14.639585865Z"}
{"msg":"Unable to find block #337489, will retry in 6.236s","level":"WARN","ts":"2023-12-15T16:31:16.779700143Z"}
{"msg":"Unable to find block #337489, will retry in 17.141s","level":"WARN","ts":"2023-12-15T16:31:23.015829111Z"}
{"msg":"Unable to compute inscription's Satoshi: block #337489 not in database","level":"ERRO","ts":"2023-12-15T16:31:40.15924017Z"}
{"msg":"Inscriptions data computation for block #775087 collected","level":"INFO","ts":"2023-12-15T16:31:40.159593944Z"}
{"msg":"Inscriptions data computation for block #775087 ended","level":"INFO","ts":"2023-12-15T16:31:40.159627221Z"}
{"msg":"Cleanup: threadpool deallocation started","level":"INFO","ts":"2023-12-15T16:31:40.159787852Z"}
{"msg":"Cleanup: threadpool deallocation ended","level":"INFO","ts":"2023-12-15T16:31:40.161352385Z"}
{"msg":"Inscription 41a183751841ef3b86b617a2fe3acaef41e6c7cc15122540b04df5ebc0b64a04i0 (#3079) detected on Satoshi 1624155815836413 (block #775087, 1204 transfers)","level":"INFO","ts":"2023-12-15T16:31:40.171143788Z"}
{"msg":"Inscription 99d0776e89ab3cf130b60f9b81bea85d14e89449225d0e6027f8ad2e6810a505i0 (#3080) detected on Satoshi 1485271863560085 (block #775087, 632 transfers)","level":"INFO","ts":"2023-12-15T16:31:40.171240211Z"}
{"msg":"Inscription 9925d3156f0dc99bbb4847351821d2a26ae4f6a4c4377972403803b4df8f4008i0 (#3081) detected on Satoshi 720397146009797 (block #775087, 692 transfers)","level":"INFO","ts":"2023-12-15T16:31:40.171295167Z"}
{"msg":"Inscription 61bf61ae9813dbcc6d7e8fbf7cd11c53bebf9a54f211a59ac759bee564145308i0 (#3082) detected on Satoshi 1758519431978480 (block #775087, 786 transfers)","level":"INFO","ts":"2023-12-15T16:31:40.17141037Z"}
...
{"msg":"Inscription 09158c40974878b4ef4e9e53bc582fa29ae609bb0eb504b6e2145abc93e52fdei0 (#3287) detected on Satoshi 1908985664123741 (block #775087, 417 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.534917044Z"}
{"msg":"Inscription 860d096b1c115d7e24786aa1a827261ec7f16a37ee3589ec41debfbc72cedadei0 (#3288) detected on Satoshi 774306456787885 (block #775087, 872 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.534953534Z"}
{"msg":"Inscription 1cd2563d3a92de6ced6293d02411eeb8603bf520771bde6397cff7a92b9c2cdfi0 (#3289) detected on Satoshi 1342458242394567 (block #775087, 1315 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.53499789Z"}
{"msg":"Inscription 888ee3c648b81febfb663dbabae365932b99b6e3e6e0a52a8f37537ee3d28edfi0 (#3290) detected on Satoshi 1458728730856920 (block #775087, 3502 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535028494Z"}
{"msg":"Inscription 038945c67d5322db281bed0c6163d713b471f290effb16313fc38c02caa58de0i0 (#3291) detected on Satoshi 1902016825684115 (block #775087, 883 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535059486Z"}
{"msg":"Inscription c252d95f05550a77f913c342fa1372268e89e0334b1a8c969be3b590c0b6cae1i0 (#3292) detected on Satoshi 377151882205556 (block #775087, 2644 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535088073Z"}
{"msg":"Inscription 769f9a872d21cda73934f5a157b1959973126e02fe4175417068d8294e8155e5i0 (#3293) detected on Satoshi 1290287356375636 (block #775087, 851 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535118421Z"}
{"msg":"Inscription c73737b0c94d378883e87c56c38ae36568313fd0b9b87baa83dbe03e57a8a8e6i0 (#3294) detected on Satoshi 436282714939553 (block #775087, 1575 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535147701Z"}
{"msg":"Inscription 0420e80c85733c93059a280c5949f6e5a154a1cf91baed4076891544309706e9i0 (#3295) detected on Satoshi 1758519432205653 (block #775087, 775 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535178751Z"}
{"msg":"Inscription 3bec6ea7fb8d24d2ca8eedcd1a2bd4c0f20cdfb2f232fcfe1e18500f226993ebi0 (#3296) detected on Satoshi 377151881580556 (block #775087, 2599 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535209019Z"}
{"msg":"Inscription a1606f8d8b4cabf64fd462e1ba1a52ea3844ae28b78a1224c4ceb252f5eda7ebi0 (#3297) detected on Satoshi 1074548074961308 (block #775087, 603 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.53524046Z"}
{"msg":"Inscription 2570fc49be547161d9263bd9aeaa0ee043aa6c315f8b7998e37ab298b94af9edi0 (#3298) detected on Satoshi 1127826600881918 (block #775087, 900 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535269703Z"}
{"msg":"Inscription f7cd9c8a9b6bab3ccb072f68f3f821f95b0664377ad9b2238feb51ebcdcecfefi0 (#3299) detected on Satoshi 1724192072391484 (block #775087, 1452 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535299665Z"}
{"msg":"Inscription 850fadd14256b3a8655cc0791dab8320e03b27e5ba153471676ae7af649a38f0i0 (#3300) detected on Satoshi 1918870789904749 (block #775087, 451 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535329958Z"}
{"msg":"Inscription 8ada9bdfa060ce57fa76ab4530e1ee3d69976dc6530e982273bf010748bd5af2i0 (#3301) detected on Satoshi 1678009589072077 (block #775087, 157 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535360105Z"}
{"msg":"Inscription 41ce4e544e33c13607cb1c3903c61baf7f39b439c34992bbeb3a7e8713a789f2i0 (#3302) detected on Satoshi 720397145945568 (block #775087, 695 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535391211Z"}
{"msg":"Inscription 1dafd434a84ccbfc0f2ff62e3137e1d89a2dc8cc1b4a2834a57bfdb86e491bf3i0 (#3303) detected on Satoshi 436282715139553 (block #775087, 1587 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535419691Z"}
{"msg":"Inscription f280cc01ecd95c455fb8905d4625d28923cef61c422aefd56ce44d419fb863f6i0 (#3304) detected on Satoshi 1571153899235607 (block #775087, 784 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535450411Z"}
{"msg":"Inscription 215b8f12569f13249becc70849001845d5549ae43f788df50fa92b6e3022d5f8i0 (#3305) detected on Satoshi 845872662600981 (block #775087, 518 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.53548257Z"}
{"msg":"Inscription 7fa39918362ead5a7da765b8bb9ec8c84d3cef0e4800038fc9be180e5f11eaf9i0 (#3306) detected on Satoshi 1737591295501891 (block #775087, 99 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535512785Z"}
{"msg":"Inscription 6fff04f9b9dcb9f5f052e8fad7f941aa9c9f4c4f210edaaf3e06849a050d06fai0 (#3307) detected on Satoshi 1571153899894299 (block #775087, 740 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535543052Z"}
{"msg":"Inscription b7d76c64887b1ef6c801265d11033585373d087831f1a37ff93f2665b09f62fbi0 (#3308) detected on Satoshi 1410541458678424 (block #775087, 1358 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535572105Z"}
{"msg":"Inscription 9030380e3075060a4b539dcdd79bb7ca5eeb771385235ebadccb36b2d7d5e4fci0 (#3309) detected on Satoshi 1562949746879201 (block #775087, 2333 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535606273Z"}
{"msg":"Inscription 7b1bad4deac151db09cd73aa47c9025e0b4691603fd7055afebec236b41a53fdi0 (#3310) detected on Satoshi 1902016849324855 (block #775087, 831 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535635616Z"}
{"msg":"Inscription 7ba07e9712fdec9967aafadec6a49c266898a80ed0d9b1158a150de9c657f6fdi0 (#3311) detected on Satoshi 1290287357325636 (block #775087, 923 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.53566526Z"}
{"msg":"Inscription c47e9837ba0a4eb5701dc934e8dba14d963df8bebe4f47c4b7e4b6f762773bffi0 (#3312) detected on Satoshi 1127826600781918 (block #775087, 890 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.53569359Z"}
{"msg":"Inscription 892648b9ea9c58663a906b6845dc8b42cf289eaf8e050d2dc497c0db670b741ci0 (#3313) detected on Satoshi 1165465341497207 (block #775087, 78 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535723229Z"}
{"msg":"Inscription 62615d463afd164447dcae0ead77c4b7ad2d363498f366661ddaeef7f065c02bi0 (#3314) detected on Satoshi 1446379692105363 (block #775087, 1710 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535754923Z"}
{"msg":"Inscription 2f52ce0d53bfbcf703ba8540265a521db85c6bf7cf7db1345dc5c3eb23295a7bi0 (#3315) detected on Satoshi 1888308309994047 (block #775087, 173 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535786265Z"}
{"msg":"Inscription 6ea505f6077d1199a70b4dc9ae1c02ffd90689f7de38b4027ba00a6a380e8662i0 (#3316) detected on Satoshi 1883996452637432 (block #775087, 399 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535817264Z"}
{"msg":"Inscription 06a59cdc38960aad232d548b5ff873c821fc43e2e37b015685c72c18111bc59ei0 (#3317) detected on Satoshi 1217429722110751 (block #775087, 1213 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535846184Z"}
{"msg":"Inscription 832442d5b7647abf1f90e1492432bd35c6a34b414cbef8505136d685b51cad5bi0 (#3318) detected on Satoshi 1197987616032863 (block #775087, 226 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.535906476Z"}
{"msg":"Inscription a473947ee7e7e061f4c40210bfa9458859449f78b81ac6b94c3eb1300ab5a9a9i0 (#3319) detected on Satoshi 1197987615912863 (block #775087, 226 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.536785374Z"}
{"msg":"Inscription 832bba509f1bcfa3f9a22522caeea8d1d7722ba1607e6fbfa4458f79c96ba043i0 (#3320) detected on Satoshi 1197987615952863 (block #775087, 226 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.536820345Z"}
{"msg":"Inscription 2bf79c79e318cebd20738cfd4142b6308a814424395c07168294b05e3be148eei0 (#3321) detected on Satoshi 1197987615992863 (block #775087, 226 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.536847519Z"}
{"msg":"Inscription 847290d2d07bfc750c0eba8cf34372f945bec0f4d961eb90a081d845a7c28280i0 (#3322) detected on Satoshi 1197987616072863 (block #775087, 226 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.536874406Z"}
{"msg":"Inscription a93d6a3f2eb393f3f4065be754457927533e1916164a0e6963c699f6a2e0088bi0 (#3323) detected on Satoshi 1197987616112863 (block #775087, 226 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.536905265Z"}
{"msg":"Inscription da6f9ab97084de4c63fd8aaa336f1c970650cb91659f1edecd95ad957ea87282i0 (#3324) detected on Satoshi 1197987614313878 (block #775087, 238 transfers)","level":"INFO","ts":"2023-12-15T15:15:38.536936347Z"}
thread 'Inscription indexing runloop' panicked at 'index out of bounds: the len is 1 but the index is 1', /src/components/ordhook-core/src/db/mod.rs:1284:24
stack backtrace:
   0:     0x5568981fba21 - std::backtrace_rs::backtrace::libunwind::trace::he648b5c8dd376705
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5568981fba21 - std::backtrace_rs::backtrace::trace_unsynchronized::h5da3e203eef39e9f
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5568981fba21 - std::sys_common::backtrace::_print_fmt::h8d28d3f20588ae4c
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5568981fba21 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd9a5b0c9c6b058c0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55689822981f - core::fmt::rt::Argument::fmt::h0afc04119f252b53
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/rt.rs:138:9
   5:     0x55689822981f - core::fmt::write::h50b1b3e73851a6fe
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/mod.rs:1094:21
   6:     0x5568981f77d7 - std::io::Write::write_fmt::h184eaf275e4484f0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/io/mod.rs:1714:15
   7:     0x5568981fb835 - std::sys_common::backtrace::_print::hf58c3a5a25090e71
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5568981fb835 - std::sys_common::backtrace::print::hb9cf0a7c7f077819
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5568981fcfa3 - std::panicking::default_hook::{{closure}}::h066adb2e3f3e2c07
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:269:22
  10:     0x5568981fcd34 - std::panicking::default_hook::h277fa2776900ff14
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:288:9
  11:     0x5568981fd529 - std::panicking::rust_panic_with_hook::hceaf38da6d9db792
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:705:13
  12:     0x5568981fd427 - std::panicking::begin_panic_handler::{{closure}}::h2bce3ed2516af7df
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:597:13
  13:     0x5568981fbe86 - std::sys_common::backtrace::__rust_end_short_backtrace::h090f3faf8f98a395
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x5568981fd172 - rust_begin_unwind
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
  15:     0x556897122893 - core::panicking::panic_fmt::h4ec8274704d163a3
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
  16:     0x5568971229f2 - core::panicking::panic_bounds_check::h11601ba3567ad740
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:162:5
  17:     0x55689728903a - ordhook::db::parse_satpoint_to_watch::h556b740a80b3d32d
  18:     0x5568972804c5 - ordhook::db::insert_inscription_in_locations::h52e4bc75ec8b9e8f
  19:     0x5568972808bf - ordhook::db::update_inscriptions_with_block::h39d4c3e70b7f9620
  20:     0x5568973d77be - ordhook::core::protocol::inscription_sequencing::augment_block_with_ordinals_inscriptions_data_and_write_to_db_tx::h226f91ae249cf186
  21:     0x55689724f8c9 - ordhook::core::pipeline::processors::inscription_indexing::process_block::hcd50acee2e3831f2
  22:     0x55689724eb90 - ordhook::core::pipeline::processors::inscription_indexing::process_blocks::h4dad5361c99abb2b
  23:     0x556897378c55 - std::sys_common::backtrace::__rust_begin_short_backtrace::h04c021a1bf03dd82
  24:     0x55689732c1b2 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2af8557af88c8ed5
  25:     0x5568982002b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc0b1022758ecac73
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
  26:     0x5568982002b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0c9654ebe7ad657e
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
  27:     0x5568982002b5 - std::sys::unix::thread::thread::new::thread_start::h04c8e9c7d83d3bd5
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7ffbe4e59ea7 - start_thread
  29:     0x7ffbe4c2fa2f - clone
  30:                0x0 - <unknown>
```
My current config is:
```
[storage]
working_dir = "/opt/ordhook"

# The Http Api allows you to register / deregister
# dynamically predicates.
# Disable by default.
#
 [http_api]
 http_port = 20456
 database_uri = "xxx"

[network]
mode = "mainnet"
bitcoind_rpc_url = "xxx"
bitcoind_rpc_username = "xxx"
bitcoind_rpc_password = "xxx"
# Bitcoin block events can be received by Chainhook
# either through a Bitcoin node's ZeroMQ interface,
# or through the Stacks node. Zmq is being
# used by default:
bitcoind_zmq_url = "xxx"
# but stacks can also be used:
# stacks_node_rpc_url = "http://0.0.0.0:20443"

[limits]
max_number_of_bitcoin_predicates = 100
max_number_of_concurrent_bitcoin_scans = 100
max_number_of_processing_threads = 200
bitcoin_concurrent_http_requests_max = 16
max_caching_memory_size_mb = 32000

# Disable the following section if the state
# must be built locally
[bootstrap]
download_url = "https://archive.hiro.so/mainnet/ordhook/mainnet-ordhook-sqlite-latest"

[logs]
ordinals_internals = true
chainhook_internals = true

```

**Comment by lgalabru** [comment]
Hi @4ker-dep! Your indexer could have been miss saving some blocks during the first step (usually occurs when the process is being interrupted). 
I'm in the process of testing [this new branch](https://github.com/hirosystems/ordhook/issues/233), that includes a scan + auto-repair when the service is being started.

**Comment by 4ker-dep** [comment]
Hi @lgalabru ! Thanks for taking the notice of my issue. I assume work on [fix/database-optims](https://github.com/hirosystems/ordhook/tree/fix/database-optims) isn't finished since the PR is not merged yet but I was eager to run this version and check for results myself. Unfortunately my **ordhook** is failing with the logs visible below.
```
...
Normal tx: {"sequence":4294967295,"txid":"91a06c989d606b7cd160e7d5f3295682f92056bae9af8e48c710b4cc762da8ad","vout":24,"scriptSig":{"hex":""},"txinwitness":["304402207b60cce781c1d11a93b3dcab6b7d98703a6276046e24566e51eb3a08bed50f3b0220207d24a2974c16bf25733555ffdaebc5c6131941d9538e3e7b396de89b523fe001","021082a582b6ba356a1134c1e1a3b5efde99f698fad103b03a5ed2ab67db23a875"],"prevout":{"height":775086,"value":0.00369921}}
Normal tx: {"sequence":4294967295,"txid":"a2c59c4faf6a3e48e54222f9994aa80f03d78785612e95b7cd11488c0eaf2df3","vout":0,"scriptSig":{"hex":""},"txinwitness":["3044022077c66e459c1c30079515dec941a4b6b92994fa00c35a1ee752653e77ebf2790d02207785f861508ea753e71b8de7ed5f062798ae65e4c355fb12df6989ec2639540d01","028d616ae07b078357084eac9ff2b2b61b69b2aad4cf098427f2ed004ea48810e9"],"prevout":{"height":775086,"value":0.00402991}}
Normal tx: {"sequence":4294967295,"txid":"ea1b1a0753b5cbccc0937e8b9ca74864c7442a880904f7c586d73a1979019069","vout":0,"scriptSig":{"hex":"1600144b36be784d502693e067e747d8f0b5783d6e26ad"},"txinwitness":["304402202132901665df6a51d89cfc56ae86300626282f1caf4d191a04a865ad09d17fb802200729323d1cdd2d8ba4a3c2ec6901e210d29952d5bb8a6ed0293e290d240d0a6e01","03fa22e49023f3ef013006d1300c73c9d6e6673d09513c777437056de1eedaf109"],"prevout":{"height":775086,"value":0.00128711}}
Normal tx: {"sequence":4294967295,"txid":"aab9ee10c4f6cc2a8db9733c20c165db530d6e5db689c199802d0083f7de282f","vout":0,"scriptSig":{"hex":""},"txinwitness":["3044022061b651c5a004383bdf3d0cba7153a7685b07953412814bb3a395a3e4f0fb77d802205819031161b0aeb1c86da1a463fe605b852ae269a565c9e704371ff3fe302f6201","034fddde7afd30966b9a50b0696e3d44e52c718aca19605288f872da67113eb118"],"prevout":{"height":775086,"value":0.01389987}}
Normal tx: {"sequence":4294967295,"txid":"26e922300c31a0796b78ae4e86550ddebd52deb1ab47eb376ced3f640467b570","vout":0,"scriptSig":{"hex":""},"txinwitness":["3044022064f3db56fd10033718aa96d4c71c35bb48025d2ec5792f38f780c21696a2450a02207b6dcac9598d4a2e169528b9c56f79cc5cf027560bd037e3f3e439062e0b976901","028d590d17a3e757c482a6d11f59fe824342360e10d34fcb8c36c24d025526252f"],"prevout":{"height":775086,"value":0.00120735}}
Normal tx: {"sequence":4294967295,"txid":"10c7fe086aeac5dc7f98e3841e676dc81cc46c27bd70221dc23a0eb0d5dd98be","vout":3,"scriptSig":{"hex":""},"txinwitness":["304402207029d9b6561b7d43b464997fc2c669c5e0fed2d222f321a595405f8cc7cb34b802206188674ff2de917bc532fa1748a673b3169bd9cca7cc8b057c4cbcf7b71e17da01","027855b665dace9739dd8ad9a3031939c94dcea9626d5d5864cb4258b878893319"],"prevout":{"height":775086,"value":0.02499}}
Normal tx: {"sequence":4294967295,"txid":"f8addfb11b81a8fc039883d748f7d6224055d1dcd328e3322d8eb248677184fd","vout":28,"scriptSig":{"hex":""},"txinwitness":["","304402204d15de2904dfba9d70b1899fff92a15a3a353b018c66509da20e44d7f4ece2ab022072b0fed8b1a8dc3fed1b87e28560a34118fc114e012583efa2d561cb9394de8a01","304402202d39faddd4a52be72b111aab3d7ba90a6dce274d2e8b60edb44b1db32622dd7a0220398d585734abffc7403e402006b6dcf056973bab21a42edd5caef36fb001b37f01","522103eea443e3d0e5e50bf4ae3ae86b73e4492df673764048797bba31d55d22ece4d9210346143acfb8593064d1e9d2e29ace974c36b6ceb10ca636e2bd2bf417bb22376f52ae"],"prevout":{"height":775029,"value":0.00085415}}
Normal tx: {"sequence":4294967293,"txid":"2f7aa1f75833b4b0cd512c103cee664c54e5437d4285a7a44d6c06ca83342c02","vout":0,"scriptSig":{"hex":""},"txinwitness":["3044022063a51b6580def22a4778b0af1fffafe7f9483c97f2515a37880edd13a95f91ff02205c5e4597402fd5d790df6c60f054fadd44f855e2a60092cf79325fafc22250ae01","03c62b38281aab4f723f869c9c34083f241bfc0f4f0ea16ecde7db1d131447f7ba"],"prevout":{"height":775081,"value":0.29177402}}
Normal tx: {"sequence":4294967295,"txid":"2d55eac8af3308a02f4155fa793c3bd25c4f19aaf3618c9451d787a49184d84b","vout":0,"scriptSig":{"hex":""},"txinwitness":["9a789669e5d4e26cee2af70d0d071276a70993b4d44c4de11a875db7c2d4bc96f144394ff1f620f5e7b4f1883bffe274c7e78d053455eccdbe3f5151acbbb59001"],"prevout":{"height":775074,"value":0.00050332}}
Normal tx: {"sequence":4294967295,"txid":"e25b318f145ae6a6b9a2ec320ce7236782bedc497ca1f29b4d917bb8fd188528","vout":0,"scriptSig":{"hex":""},"txinwitness":["e4537394eef645b1d6e092e69654ad30f689918cc7e0c88e2a353dde568a832a3ce5b3698a612b45f8d8a793302ba15282c2fe1c3d902fcb298448b9624c876001"],"prevout":{"height":775074,"value":0.00049474}}
Normal tx: {"sequence":4294967295,"txid":"a246d57fa50a2630b5874b038d6d0b6b17aaf12e245cb04a75e12f109d1da1c4","vout":0,"scriptSig":{"hex":""},"txinwitness":["9cbcdd596f136113e853e8eddd2d1ea7840d48a49e5407584fe78abff7f9a3cc52e8ee803f034f5f55cb9c030669e3d5b799a27cd188f3c7e1fb593ed4cde5bd01"],"prevout":{"height":775074,"value":0.00006332}}
Normal tx: {"sequence":4294967295,"txid":"3ce7adcfbb85cd7597c0c27e5360053ca29acf56f25ad252eefbbaa963845b58","vout":0,"scriptSig":{"hex":""},"txinwitness":["7a19d7c70b01785081473dc63ac901b76f9f20b26fa17b521f5367dc2545ea8214299dc0028a8c49ca355f9632c85c8b36d3e721061a2e44ea269dbcae3f32ac01"],"prevout":{"height":774949,"value":8.58e-6}}
Normal tx: {"sequence":4294967295,"txid":"2330679c8c6c39cf638b22a4af631476a80950b54510c13bc4ed4beb41bd94e7","vout":0,"scriptSig":{"hex":""},"txinwitness":["fcdd49403654e5e79a591fc972eea997368b0b344cd2fa641213cc4a50a189aa3e42eaca3618310a59a8bc60e85030d80a3efc865bba70d2c3f872004f6839a801"],"prevout":{"height":775087,"value":0.00005317}}
Normal tx: {"sequence":2147483648,"txid":"7746547002c8c792fc46acab252707375d52e8db98429febe2eaf5004c70fd66","vout":0,"scriptSig":{"hex":""},"txinwitness":["3045022100a5ca9ad13c630bbd7e69292f8043e80a90bdc572f51049cb42237469534d9cb002201ec5d796a7355a2ee4c8e5870c479da072fbdac7763d3e47deb6aee1f9ce8a3301","028341332bd4ea53d37fce64f0b64eeba72a958d002a2379e27347b96b3df17ab4"],"prevout":{"height":775087,"value":0.00039322}}
Normal tx: {"sequence":2147483648,"txid":"5d8fe5fad25c8ff2c4f22fff80bcb164d45fbfb3febe6671c92189cac8d67abe","vout":1,"scriptSig":{"hex":""},"txinwitness":["304402206669b1f6e41e535f3ba98999956fa67d5e33fdae820d17eb32f81f141fee4fed02201eb85b073e918bdc9355c4a4b5686916092643966e440a9d5c4c6f00978978b801","0322177250812306558dce8482012523a01501f2fdcf457d6cc40008053a79d630"],"prevout":{"height":775083,"value":0.00219453}}
Dec 19 12:26:08.688 INFO Processing 2 blocks
Dec 19 12:26:08.690 INFO Inscriptions data computation for block #775087 started
Dec 19 12:26:08.696 INFO Number of inscriptions in block #775087 to process: 247 (L1 cache hits: 0, queue: [775088], L1 cache len: 0, L2 cache len: 0)
Dec 19 12:26:09.954 ERRO fatal: unable to retrieve tx ancestor 8a720f7d219f536b in block 775034 (satpoint 344a16e8735031dd692fd015ef7a12ecd5136680a4c75730c51f246dd2c1db6a:0)

```

**Comment by lgalabru** [comment]
@4ker-dep yeah this PR will require you to restart an index from scratch unfortunately.
I was able to test this PR locally successfully, it's been deployed to a cloud environnement - I'd like to see it running for a few days first, before merging.
